const express = require('express');
const userMappingController = require('../controllers/userMapping.controller');
const { authenticateToken } = require('../middleware/auth.middleware');

const router = express.Router();

// Middleware de autenticación para todas las rutas
router.use(authenticateToken);

/**
 * @swagger
 * /api/user-mappings/auto-generated:
 *   get:
 *     summary: Obtener reporte de usuarios auto-generados
 *     tags: [User Mappings]
 *     parameters:
 *       - in: query
 *         name: sourceAreaId
 *         schema:
 *           type: string
 *         description: ID del área origen (opcional)
 *     responses:
 *       200:
 *         description: Reporte obtenido exitosamente
 */
router.get('/auto-generated', userMappingController.getAutoGeneratedUsers);

/**
 * @swagger
 * /api/user-mappings/contexts:
 *   get:
 *     summary: Obtener contextos disponibles para usuarios
 *     tags: [User Mappings]
 *     responses:
 *       200:
 *         description: Lista de contextos disponibles
 */
router.get('/contexts', (req, res) => {
    const contexts = userMappingController.getAvailableContexts();
    res.json({
        success: true,
        data: contexts,
        message: 'Contextos disponibles obtenidos exitosamente'
    });
});

/**
 * @swagger
 * /api/user-mappings/area/{areaId}:
 *   get:
 *     summary: Obtener mapeos de usuario por área
 *     tags: [User Mappings]
 *     parameters:
 *       - in: path
 *         name: areaId
 *         required: true
 *         schema:
 *           type: string
 *         description: ID del área
 *     responses:
 *       200:
 *         description: Mapeos obtenidos exitosamente
 */
router.get('/area/:areaId', userMappingController.getFieldMappings);

/**
 * @swagger
 * /api/user-mappings/area/{areaId}:
 *   post:
 *     summary: Crear nuevo mapeo de usuario
 *     tags: [User Mappings]
 *     parameters:
 *       - in: path
 *         name: areaId
 *         required: true
 *         schema:
 *           type: string
 *         description: ID del área
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - sourceField
 *               - targetField
 *               - context
 *             properties:
 *               sourceField:
 *                 type: string
 *                 description: Nombre de la columna en Excel
 *               targetField:
 *                 type: string
 *                 description: Campo en la base de datos
 *               context:
 *                 type: string
 *                 description: Contexto del usuario (sales_manager, architect, etc.)
 *               isRequired:
 *                 type: boolean
 *                 description: Si el campo es requerido
 *               description:
 *                 type: string
 *                 description: Descripción del mapeo
 *     responses:
 *       200:
 *         description: Mapeo creado exitosamente
 */
router.post('/area/:areaId', userMappingController.createUserMapping);

/**
 * @swagger
 * /api/user-mappings/area/{areaId}/setup-common:
 *   post:
 *     summary: Configurar mapeos comunes para un área
 *     tags: [User Mappings]
 *     parameters:
 *       - in: path
 *         name: areaId
 *         required: true
 *         schema:
 *           type: string
 *         description: ID del área
 *     responses:
 *       200:
 *         description: Mapeos comunes configurados
 */
router.post('/area/:areaId/setup-common', userMappingController.setupCommonMappings);

/**
 * @swagger
 * /api/user-mappings/{mappingId}:
 *   put:
 *     summary: Actualizar mapeo de usuario
 *     tags: [User Mappings]
 *     parameters:
 *       - in: path
 *         name: mappingId
 *         required: true
 *         schema:
 *           type: string
 *         description: ID del mapeo
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               sourceField:
 *                 type: string
 *               targetField:
 *                 type: string
 *               context:
 *                 type: string
 *               isRequired:
 *                 type: boolean
 *               description:
 *                 type: string
 *               isActive:
 *                 type: boolean
 *     responses:
 *       200:
 *         description: Mapeo actualizado exitosamente
 */
router.put('/:mappingId', userMappingController.updateUserMapping);

module.exports = router;