const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

/**
 * Servicio para auto-creación de usuarios durante importación Excel
 */
class UserAutoCreationService {

  /**
   * Busca o crea usuario según el contexto (puesto)
   */
  async findOrCreateUser(name, context, sourceAreaId) {
    if (!name) return null;

    // Primero buscar si ya existe
    const existingUser = await this.findExistingUser(name);
    if (existingUser) {
      return existingUser.id;
    }

    // Si no existe, crear nuevo usuario
    return await this.createUserByContext(name, context, sourceAreaId);
  }

  /**
   * Busca usuario existente por nombre
   */
  async findExistingUser(name) {
    const user = await prisma.user.findFirst({
      where: {
        OR: [
          { firstName: { contains: name, mode: 'insensitive' } },
          { lastName: { contains: name, mode: 'insensitive' } },
          {
            AND: [
              { firstName: { contains: name.split(' ')[0], mode: 'insensitive' } },
              { lastName: { contains: name.split(' ').slice(1).join(' '), mode: 'insensitive' } }
            ]
          }
        ],
        isActive: true
      }
    });

    return user;
  }

  /**
   * Crea usuario según el contexto/puesto
   */
  async createUserByContext(name, context, sourceAreaId) {
    const { role, email, defaultArea } = this.determineUserProfile(name, context, sourceAreaId);

    const nameParts = name.trim().split(' ');
    const firstName = nameParts[0];
    const lastName = nameParts.slice(1).join(' ') || firstName;

    // Generar password temporal
    const tempPassword = this.generateTempPassword();
    const hashedPassword = await bcrypt.hash(tempPassword, 10);

    const newUser = await prisma.user.create({
      data: {
        email,
        firstName,
        lastName,
        role,
        areaId: defaultArea,
        password: hashedPassword,
        isActive: true,
        // Nota: Como el schema no tiene campo metadata,
        // podrías agregar estos datos a un campo de notas
        // o crear una tabla separada para tracking
        isActive: true
      }
    });

    console.log(`✅ Usuario auto-creado: ${firstName} ${lastName} (${role}) - Email: ${email}`);

    return newUser.id;
  }

  /**
   * Determina perfil del usuario según el contexto
   */
  determineUserProfile(name, context, sourceAreaId) {
    const cleanName = name.toLowerCase().replace(/[^\w\s]/g, '');
    const baseEmail = this.generateEmail(name);

    // Mapeo de contextos a roles y configuraciones
    const contextMappings = {
      // Ventas
      'sales_manager': {
        role: 'COORDINADOR',
        emailPrefix: 'ventas',
        defaultArea: sourceAreaId
      },
      'sales_executive': {
        role: 'COLABORADOR',
        emailPrefix: 'ventas',
        defaultArea: sourceAreaId
      },
      'sales_leader': {
        role: 'COORDINADOR',
        emailPrefix: 'ventas',
        defaultArea: sourceAreaId
      },

      // Diseño
      'architect': {
        role: 'COLABORADOR',
        emailPrefix: 'arquitectura',
        defaultArea: sourceAreaId
      },
      'design_manager': {
        role: 'COORDINADOR',
        emailPrefix: 'diseno',
        defaultArea: sourceAreaId
      },
      'design_coordinator': {
        role: 'COORDINADOR',
        emailPrefix: 'diseno',
        defaultArea: sourceAreaId
      },

      // Genérico
      'default': {
        role: 'COLABORADOR',
        emailPrefix: 'usuario',
        defaultArea: sourceAreaId
      }
    };

    const config = contextMappings[context] || contextMappings['default'];

    return {
      role: config.role,
      email: `${config.emailPrefix}.${baseEmail}@empresa.com`,
      defaultArea: config.defaultArea
    };
  }

  /**
   * Genera email base desde el nombre
   */
  generateEmail(name) {
    return name.toLowerCase()
      .replace(/[^\w\s]/g, '')
      .split(' ')
      .join('.');
  }

  /**
   * Genera password temporal
   */
  generateTempPassword() {
    return 'Temp' + Math.random().toString(36).slice(-8) + '!';
  }

  /**
   * Obtiene reporte de usuarios auto-generados
   * Nota: Por ahora retorna usuarios recientes (ya que no tenemos campo metadata)
   * TODO: Crear tabla separada para tracking de usuarios auto-generados
   */
  async getAutoGeneratedUsersReport(sourceAreaId = null) {
    const where = {
      isActive: true
    };

    if (sourceAreaId) {
      where.areaId = sourceAreaId;
    }

    // Por ahora, obtener usuarios creados en los últimos 30 días
    // como aproximación de usuarios auto-generados
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    where.createdAt = {
      gte: thirtyDaysAgo
    };

    const users = await prisma.user.findMany({
      where,
      select: {
        id: true,
        firstName: true,
        lastName: true,
        email: true,
        role: true,
        createdAt: true,
        area: {
          select: {
            name: true
          }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    return users.map(user => ({
      ...user,
      // Como no tenemos metadata, inferir información del email
      tempPassword: 'Ver logs del servidor',
      context: this.inferContextFromEmail(user.email),
      createdFrom: 'excel_import_inferred'
    }));
  }

  /**
   * Infiere el contexto desde el email
   */
  inferContextFromEmail(email) {
    if (email.includes('ventas.')) return 'sales_related';
    if (email.includes('arquitectura.')) return 'architect';
    if (email.includes('diseno.')) return 'design_related';
    return 'unknown';
  }
}

module.exports = new UserAutoCreationService();